yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    # Профайл пользователя
    path('profile/<str:username>/', views.profile, name='profile'),
    # Просмотр записи
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('group/<slug:slug>/', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .validators import validate_not_empty

# Обращение к пользовалям делается через метод в соответствии с документацией
User = get_user_model()
# Create your models here.


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        validators=[validate_not_empty],
        verbose_name='Текст',
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        blank=True,  # (Позволяет занести в поле пустое значение)
        null=True,  # (Будет хранить пустые значения)
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )

    def __str__(self) -> str:
        return self.text[:15]

    class Meta:
        ordering = ("-pub_date",)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='post',
        help_text='Комментарий')
    name = models.CharField(max_length=80)
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Оставьте свой комментарий здесь')
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE)
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True)

    class Meta:
        ordering = ('created',)
        verbose_name_plural = 'Коментарии'
        verbose_name = 'Коментарий'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

    class Meta:
        # удобое читаемое имя в множественнои и единственном числе
        verbose_name_plural = 'Подписки'
        verbose_name = 'Подписка'
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_author_user_following'
            )
        ]

    def __str__(self):
        return f'{self.user} подписался на {self.author}'

yatube/posts/forms.py
# Импортируем модуль forms, из него возьмём класс ModelForm
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {"text": "Текст", "group": "Группа"}
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        localized_fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group, User, Comment, Follow
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .utils import paginate_page
from django.views.decorators.cache import cache_page

# Create your views here.


# Главная страница
@cache_page(20)
def index(request):

    # post_list = Post.objects.all().order_by('-pub_date')
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядить так:
    posts = Post.objects.select_related("group", "author")
    # вызов метода пагинации
    page_obj = paginate_page(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


# Страница с постами группы
def group_posts(request, slug):

    template = 'posts/group_list.html'
    # Функция get_object_or_404 получает по заданным критериям объект
    # из базы данных или возвращает сообщение об ошибке, если объект не найден.
    # В нашем случае в переменную group будут переданы объекты модели Group,
    # поле slug у которых соответствует значению slug в запросе
    group = get_object_or_404(Group, slug=slug)

    # Метод .filter позволяет ограничить поиск по критериям.
    # Это аналог добавления
    # условия WHERE group_id = {group_id}
    # posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    group_posts = group.posts.all()
    page_obj = paginate_page(request, group_posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


# Профиль пользователя
def profile(request, username):

    template = 'posts/profile.html'
    user_author = get_object_or_404(User, username=username)

    # такая конструкция ниже тоже работает, но не проходит автотесты
    # user_posts = get_list_or_404(Post, author__username=username)
    # user_posts_count = user404.posts.select_related('author').count()

    user_posts = user_author.posts.all()
    page_obj = paginate_page(request, user_posts)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user_author
    ).exists()
    context = {
        'page_obj': page_obj,
        'following': following,
        'user_author': user_author,
    }
    return render(request, template, context)


# Посты пользователя
def post_detail(request, post_id):

    template = 'posts/post_detail.html'
    post = get_object_or_404(
        Post.objects.select_related(
            'author',
            'group'
        ),
        pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'comments': comments,
        'post': post,
        'form': form,
    }
    return render(request, template, context)

# @login_required
# def post_create(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST or None)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect('posts:profile', post.author)
#     form = PostForm()
#     return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_create(request):

    form = PostForm(
        request.POST or None,
        files=request.FILES or None)

    if not request.method == "POST":
        return render(
            request,
            "posts/create_post.html",
            {"form": form, "is_edit": False}
        )

    if not form.is_valid():
        return render(
            request,
            "posts/index.html",
            {"form": form, "is_edit": False}
        )
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect("posts:profile", request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id)
    context = {
        "form": form,
        "post": post,
        "is_edit": True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    # Получите пост
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """получаем посты в которых author связан через модель Follows
    текущим пользователем через request идем в Post, от туда через filter
     в author, далее через select_related (following) в Follow, далее user.
     Находим пользователя с заданным именем - для него ищем обьекты в
     таблицы Follow которые на него ссылаются далее для всех найденых з
     аписей в Follow ищутся связанные с ним авторы,
     а далее все посты которые связаны с автором"""
    posts_lists = Post.objects.filter(author__following__user=request.user)
    context = {'page_obj': paginate_page(request, posts_lists)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Получаем всех автров"""
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    """Получаем всех подписанных юзеров и отписываем их"""
    author = get_object_or_404(User, username=username)
    follow_qs = Follow.objects.filter(author=author, user=request.user)
    if follow_qs.exists():
        follow_qs.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Добавить запись
  {% endif %} 
{% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if is_edit %}
                Редактирование поста
                {% else %}
                Новый пост   
                {% endif %}       
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data"
                  {% if is_edit %}
                    action="{% url 'posts:post_edit' post_id=post.pk %}"
                  {% else %}
                    action="{% url 'posts:post_create' %}"
                  {% endif %}
                >
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text }}              
                    <small id="id_text-help" class="form-text text-muted">
                      {% if is_edit %}
                      Отредактированный пост
                      {% else %}
                      Текст нового поста
                      {% endif %}    
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_image">
                      Картинка                      
                    </label>
                    <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                      Сохранить
                      {% else %}
                      Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% load thumbnail %}
{% block title %} Подписки {% endblock %}
{% block content %}
<div class="container py-5">
  {% include 'posts/includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
  <div class="container py-3">
    <article>
      {% include 'posts/post.html' %}
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-link">Все записи группы - "{{ post.group }}"</a>
      {% endif %}
    </article>
  </div>
</div>
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
<div class="d-flex justify-content-center">
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}{{ group.slug }}{% endblock %}
{% block content %}
{% load thumbnail %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{group.description}}</p>
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  </article>
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %} 

{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  <div class="container py-3">
    <article>
      {% include 'posts/post.html' %}
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}" class="btn btn-link">Все записи группы - "{{ post.group }}"</a>
      {% endif %}
    </article>
  </div>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post.html
{% load thumbnail %} 
<article>
    <ul>
      <li>
        Автор: {{ user_author }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
   {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
     <img class="card-img my-2" src="{{ im.url }}">
   {% endthumbnail %}
    <p>{{ post.text}}</p>
   </p>
   <a href="{% url 'posts:post_detail' post.pk%}">подробная информация </a><hr>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
   </article>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% block title %}{{ post.text|slice:":30" }}{% endblock %} 
{% block content %}
{% load thumbnail %}
{% load user_filters %}
<div class="container py-5">         
      <div class="row"> 
        <aside class="col-12 col-md-3"> 
          <ul class="list-group list-group-flush"> 
            <li class="list-group-item"> 
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li> 
            {% if post.group %}    
            <li class="list-group-item"> 
              Группа: {{ post.group }} 
              <a href="{% url 'posts:group_list' post.group.slug %}"> 
                все записи группы 
              </a> 
            {% endif %} 
            </li> 
            <li class="list-group-item"> 
              Автор: {{ post.author }} 
            </li> 
            <li class="list-group-item d-flex justify-content-between align-items-center"> 
              Всего постов автора:  <span>{{ post.author.posts.count }}</span> 
            </li> 
            <li class="list-group-item"> 
              <a href="{% url 'posts:profile' post.author %}"> 
                все посты пользователя 
              </a> 
            </li> 
          </ul> 
        </aside> 
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p> 
          {% if user == post.author %} 
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.pk %}"> 
            редактировать запись 
          </a>     
          {% endif %} 
        </article>
        {% load user_filters %}
        {% if comments.count != 0 %}
        {% with comments.count as total_comments %}
        <hr>
        <figure>
          <blockquote class="blockquote">
            <div class="shadow-sm p-2 bg-white rounded">
              Комментариев {{ total_comments }}
            </div>
          </blockquote>
        </figure>
        {% endwith %}
        {% endif %}
        {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить комментарий</button>
            </form>
          </div>
        </div>
        {% endif %}
        {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <div class="alert alert-primary" role="alert">
              {{ comment.created|date:'d E Y' }}
              <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.get_full_name }}</a>
            </div>
            <figure>
              <blockquote class="blockquote">
                <div class="shadow-sm p-3 bg-white">
                  {{ comment.text|linebreaks }}
                </div>
              </blockquote>
            </figure>
          </div>
        </div>
        {% empty %}
        <hr>
        <figure>
          <blockquote class="blockquote">
            <div class="shadow-sm p-2 bg-white rounded">
              Сделай это первым!
            </div>
          </blockquote>
        </figure>
        {% endfor %} 
      </div>  
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% if author.get_full_name %}
{{ author.get_full_name }}
{% else %}
{{ author.username }}
{% endif %}
Профайл пользователя
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="card-body">
      <h1 class="card-title">Все посты пользователя
        {% if user_author.get_full_name %}{{ user_author.get_full_name }}
        {% else %}{{ user_author.username }}
        {% endif %}
      </h1>
      <h3 class="card-text">Всего постов: {{ user_author.posts.count }} </h3>
      {% if following %}
      <a class="btn btn-lg btn-light"
         href="{% url 'posts:profile_unfollow' user_author.username %}" role="button">
        Отписаться
      </a>
      {% else %}
      <a class="btn btn-lg btn-primary"
         href="{% url 'posts:profile_follow' user_author.username %}" role="button">
        Подписаться
      </a>
      {% endif %}
</div>
{% load thumbnail %} 
{% for post in page_obj %}
{% include 'posts/post.html' %}
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/update_post.html
{% extends "base.html" %}
{% block title %}Редактировать пост{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}